#!/usr/bin/env bash
# Displays a list of currently running processes.
# Shows all processes, for all users, including those, which might not have a TTY.

ps -eo user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,command
