#!/usr/bin/env bash
# Displays the PID along with the process name, of 
# processes whose name contains the word "bash".

pids=$(pgrep -f bash)

# Loop through the PIDs and display their PID and process name
for pid in $pids; do
  process_name=$(ps -p $pid -o comm=)
  echo "$pid $process_name"
done
