#!/usr/bin/env bash
# Displays the PID along with the process name, of 
# processes whose name contains the word "bash".

pgrep bash -l

for pid in $pids; do
  process_name=$(ps -p $pid -o comm=)
  echo "$pid $process_name"
done
