#!/usr/bin/env bash
# Configures an Ubuntu server as follows:
#   - localhost resolves to 127.0.0.2
#   - facebook.com resolves to 8.8.8.8

localhost_ip="127.0.0.2"
facebook_ip="8.8.8.8"

echo -e "$localhost_ip\tlocalhost" >> /etc/hosts
echo -e "$facebook_ip\tfacebook.com" >> /etc/hosts
